### ISSUE TITLE
Current recording start/end times appear incorrect

### ISSUE THREAD

**Issue by kangaroomadman** [RogerSelwyn/skyq_remote#11]
When a recordings status is currently `RECORDING`, the `ast` field is used as the start time instead of `st`. It looks like `ast` may be the time the actual recording starts so the start isn't cut off, and will typically be 2 minutes before the scheduled programme time.

This probably isn't an issue, apart from the fact the end time is calculated from this by adding the `schd` field value which will be exact and not plus 2 x additional recording time.

The is results in programmes that were on between 20:30 and 21:00 showing as recording between 20:28 and 20:58. When this gets converted to a `RECORDED` state then the start/end times are then reported correctly.

Can we potentially just drop the processing of the `ast` field in favour of `st` all the time?

**Comment by RogerSelwyn** [comment]
This is an interesting one and thanks for raising. You can't just stop `ast` completely because as far as I can see `st` isn't present for items that have finished recording (`RECORDED`) - have a look at what is returned from this - `http://192.168.1.xxx:9006/as/pvr/?limit=1000&offset=0`. 

For scheduled there is an st/schd pair. For recorded there is an ast/finald pair (plus schd). So recording is the transition. 

Recognising that ast+schd is wrong, do we do st+schd? 
- If we do, what happens when the programme starts early or late (who knows why)? 
- Also what happens if you start recording part way through, because I can see that then you have an ast which shows what time it actually started recording which is after st, but there is nothing to indicate when it should end. That said, there is an `fr` attribute which indicates whether the start has been missed. 

So I could do:
- Starttime = ast
- Endtime
  - If fr set - st+schd
  - If fr not set the > of ast+schd or st+schd

Yes this means the times may change when moving from recording to recorded, but I think accurately represents what is going on as best I can see how.

**Comment by RogerSelwyn** [comment]
Or I can expose all the data and you can calculate as you like

**Comment by kangaroomadman** [comment]
Yes, there are lots of combinations going on....

From what I could see from my box, `st` will only not exist for downloaded programmes (where `downloadlink` is present).

I think what you have implemented in 3994991 covers the cases, so thank you!

**Comment by RogerSelwyn** [comment]
Interesting insight. At the moment I'm preferring ast over st for recorded programmes, since I'm trying to display actual where possible.

Also src is VOD for downloads. Not really checked as to what ast is showing for them, and what it will do if the programme was never broadcast Live and therefore had no planned start time.

Testing it through in my home setup at the mo.

**Comment by RogerSelwyn** [comment]
Fixed in previous release
