### ISSUE TITLE
Open a SkyQ App using pyskyqremote

### ISSUE THREAD

**Issue by stefano-sb** [RogerSelwyn/skyq_remote#16]
Hi, first of all thanks for the fantastic pyskyqremote.py tool!! I little question... Is there possibile to open a SkyQ app (es Netflix, Dazn, etc..) via pyskyqremote without menu navigation? (menu -> down, down, down, ....., down -> right, right, .... -> OK).
I noticed that using a vocal command from physical SkyQ remote the app is opened immediatly. Is there possibile to "simulate" the same command from pyskyqremote.py?

Thanks

Stefano

**Comment by RogerSelwyn** [comment]
Simple answer not that I know of. When you do a spoken command, it will be interpreted by the Sky Q box (the remote has a Bluetooth connection to the box), not by the remote. I know of no way of sending a voice command via the api. I also know of no way of sending a command to load an app (otherwise I’d have done it already, I’ve been asked loads of times), you can do what the buttons on the remote can do. Bear in mind the api is not published, so there may be options that I’m just not aware of.
