### ISSUE TITLE
New Feature: Add support for changing SkyQ stb settings

### ISSUE THREAD

**Issue by gitothy** [RogerSelwyn/skyq_remote#7]
Would it be possible to add functionality to enable changes to the [settings](https://ibb.co/n11z5n0) on the SkyQ box?  It's be really useful to change 'Picture resolution', 'Digital audio output HDMI', bluetooth pairing, etc as part of a 1 click automation and without interrupting viewing.

I'm not sure if the end points are known for any of these?  If not I was thinking you could do a certain amount with button push combos as the menu layout seems to be static for all STBs.  It would be a bit clunky and only really works for settings that are an on/off toggle, but would be a start.

If you think there may be undiscovered endpoints for the settings that and no-one's already looked then let me know and I'm happy to go on the hunt.  Hopefully not a wild goose chase!

Otherwise just to say this is great work here that benefits many and is much appreciated 👍

**Comment by RogerSelwyn** [comment]
Thanks for thinking of this. I'm not aware of any other api endpoints, though I'm happy for you to do some research and I'll try to incorporate if I can. To be honest, what I would anticipate to be available are endpoints that achieve what the remote can do (send button presses) and what any official Sky App can do. I son't use the apps a lot, but I don't think they can configure settings.

You can create your own command sequence using the (custom) sources options, which will play back the configured set of buttons - https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#sources

You could the potentially write an automation to run the sequence whenever it sees the SkyQ box change to a certain channel. However, of course this would interrupt viewing since it is just imitating what you would do with the remote.

**Comment by RogerSelwyn** [comment]
Closing, since no known api.

**Comment by gitothy** [comment]
Yeah soz Rog, I got nowhere with this one.
